name: online_shop
description: A new Flutter e-commerce project following university requirements.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.2
  go_router: ^14.0.0
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1

  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.8.3

  # Image handling
  image_picker: ^1.0.7

  # Functional programming and utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/light.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/light.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/light.png
    - assets/images/dark.png
